source 'https://rubygems.org'

gem 'minitest', '~> 5.10'
gem 'simplecov', '~> 0.14'
gem 'kitchen-vagrant'
gem 'inspec'
gem 'pry'
gem 'test-kitchen'
gem 'kitchen-inspec'
gem 'json', '~> 2.1.0'
gem 'CFPropertyList', '~> 2.3', '>= 2.3.5'
gem 'activesupport'
